server:
  port: 8089

spring:
  application:
    name: bill-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: infohotelease@gmail.com
    password: dwhgxkxdpgkzgrzy
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/bill_db
    username: root
    password: admin@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
