server:
  port: 8083

logging:
  file:
    name: logs/guest-service.log
  level:
    root: INFO
    com.hotel.guest_service.controller.GuestController: DEBUG


spring:
  application:
    name: guest-service
  datasource:
    url: jdbc:mysql://localhost:3306/guest
    username: root
    password: admin@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
